"""Contract-driven Rust generation: KernelSpec → std-only Rust kernel.

Deterministic rendering — the same spec always yields byte-identical Rust.
Only mechanical repairs (casts, names) may touch the output afterwards;
semantic changes require a new spec, never a hand-edit.
"""

from __future__ import annotations

_CMP = {"lt": "<", "le": "<=", "gt": ">", "ge": ">=", "eq": "==", "ne": "!="}
_ARITH = {"add": "+", "sub": "-", "mul": "*", "div": "/"}


def _rust_type(type_: str) -> str:
    return {"f64": "f64", "int": "i64", "bool": "bool"}[type_]


def _fmt_const(node: dict) -> str:
    value, type_ = node["value"], node.get("type", "f64")
    if type_ == "bool":
        return "true" if value else "false"
    if type_ == "int":
        return str(int(value))
    text = repr(float(value))
    return text if "." in text or "e" in text.lower() else text + ".0"


def _coerce(node: dict, target: str) -> dict:
    if target == "f64" and node.get("op") == "const" and node.get("type") == "int":
        return {"op": "const", "type": "f64", "value": node["value"]}
    return node


def render_expr(node: dict, wrap: bool = True) -> str:
    op = node["op"]
    if op == "const":
        text = _fmt_const(node)
    elif op == "var":
        text = node["name"]
    elif op == "not":
        text = f"!{render_expr(node['arg'])}"
    elif op in ("and", "or"):
        joiner = " && " if op == "and" else " || "
        text = joiner.join(render_expr(a) for a in node["args"])
    elif op == "cmp":
        left, right = node["left"], node["right"]
        if left.get("type") == "f64" or right.get("type") == "f64":
            left, right = _coerce(left, "f64"), _coerce(right, "f64")
        text = f"{render_expr(left)} {_CMP[node['cmp']]} {render_expr(right)}"
    elif op in ("add", "sub", "mul", "div"):
        left, right = node["left"], node["right"]
        if left.get("type") == "f64" or right.get("type") == "f64":
            left, right = _coerce(left, "f64"), _coerce(right, "f64")
        text = f"{render_expr(left)} {_ARITH[op]} {render_expr(right)}"
    elif op == "abs":
        text = f"{render_expr(node['arg'])}.abs()"
    elif op == "neg":
        text = f"-{render_expr(node['arg'])}"
    elif op == "if":
        text = (
            f"if {render_expr(node['cond'], wrap=False)} "
            f"{{ {render_expr(node['then'], wrap=False)} }} "
            f"else {{ {render_expr(node['else'], wrap=False)} }}"
        )
    else:
        raise ValueError(f"unknown expr op: {op}")
    needs_wrap = wrap and op not in ("const", "var")
    return f"({text})" if needs_wrap else text


def render_kernel(spec_dict: dict, module_doc: str = "") -> str:
    """Render a complete self-contained Rust module for the spec."""
    lines = [
        "//! AUTO-GENERATED by the VAYREN migration agent — do not hand-edit.",
        "//!",
        "//! Source contract: RiskEngine::_evaluate scalar checks. Regenerate",
        "//! from the KernelSpec on any contract change; semantic hand-edits",
        "//! are forbidden (parity would fail).",
    ]
    if module_doc:
        lines.append(f"// {module_doc}")
    lines.append("")
    lines.append("#[derive(Debug, Clone, Copy)]")
    lines.append("pub struct RiskKernelInputs {")
    for entry in spec_dict["inputs"]:
        lines.append(f"    pub {entry['name']}: {_rust_type(entry['type'])},")
    lines.append("}")
    lines.append("")
    lines.append("/// Number of kernel checks (bitmask width).")
    lines.append(f"pub const CHECK_COUNT: usize = {len(spec_dict['checks'])};")
    lines.append("")
    for check in spec_dict["checks"]:
        lines.append(f"/// Bit {check['bit']}: `{check['name']}`.")
        lines.append(f"pub const BIT_{check['name'].upper()}: u32 = 1 << {check['bit']};")
    lines.append("")
    lines.append("/// Pure scalar policy checks. Bit i set ⟺ checks[i] passed.")
    lines.append("pub fn evaluate_risk_kernel(inputs: &RiskKernelInputs) -> u32 {")
    for entry in spec_dict["inputs"]:
        rust_type = _rust_type(entry["type"])
        lines.append(f"    let {entry['name']}: {rust_type} = inputs.{entry['name']};")
    lines.append("    let mut mask: u32 = 0;")
    for check in spec_dict["checks"]:
        lines.append(f"    if {render_expr(check['expr'], wrap=False)} {{")
        lines.append(f"        mask |= BIT_{check['name'].upper()};")
        lines.append("    }")
    lines.append("    mask")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _split_inputs(spec_dict: dict) -> tuple[list, list, list]:
    f64 = [e for e in spec_dict["inputs"] if e["type"] == "f64"]
    ints = [e for e in spec_dict["inputs"] if e["type"] == "int"]
    bools = [e for e in spec_dict["inputs"] if e["type"] == "bool"]
    return f64, ints, bools


def render_sandbox_harness(spec_dict: dict, vectors: list[tuple[dict, int]]) -> str:
    """Render a self-contained Rust differential test (candidate vs masks)."""
    f64, ints, bools = _split_inputs(spec_dict)

    def lit_f64(value: object) -> str:
        text = repr(float(value))  # type: ignore[arg-type]
        return text if "." in text or "e" in text.lower() else text + ".0"

    lines = [
        "//! AUTO-GENERATED sandbox differential: candidate vs pinned masks.",
        "use kernel_probe::risk_kernel::{evaluate_risk_kernel, RiskKernelInputs};",
        "",
        "fn case(f: &[f64], i: &[i64], b: &[bool], want: u32) {",
        "    let mut pos_f = 0usize;",
        "    let mut pos_i = 0usize;",
        "    let mut pos_b = 0usize;",
        "    let mut take_f = || { let v = f[pos_f]; pos_f += 1; v };",
        "    let mut take_i = || { let v = i[pos_i]; pos_i += 1; v };",
        "    let mut take_b = || { let v = b[pos_b]; pos_b += 1; v };",
        "    let inputs = RiskKernelInputs {",
    ]
    for entry in spec_dict["inputs"]:
        if entry["type"] == "f64":
            lines.append(f"        {entry['name']}: take_f(),")
        elif entry["type"] == "int":
            lines.append(f"        {entry['name']}: take_i(),")
        else:
            lines.append(f"        {entry['name']}: take_b(),")
    lines += [
        "    };",
        "    assert_eq!(evaluate_risk_kernel(&inputs), want);",
        "}",
        "",
        "#[test]",
        "fn differential_masks() {",
    ]
    for env, want in vectors:
        f_vals = ", ".join(lit_f64(env[e["name"]]) for e in f64)
        i_vals = ", ".join(str(int(env[e["name"]])) for e in ints)
        b_vals = ", ".join("true" if env[e["name"]] else "false" for e in bools)
        lines.append(f"    case(&[{f_vals}], &[{i_vals}], &[{b_vals}], {want:#x});")
    lines += ["}", ""]
    _ = (ints, bools)
    return "\n".join(lines)


__all__ = ["render_expr", "render_kernel", "render_sandbox_harness"]
