"""Frozen-oracle generation: original logic snapshotted for differential parity.

The oracle is a mechanical transform of the pre-migration implementation
(verbatim semantics, standalone signature). It is written once to
``scripts/migration/agent/oracles/`` and imported by the generated parity
test, the parity harness and the shadow runner. Production files must never
import it — the validator fails closed on any such import.
"""

from __future__ import annotations

import ast
import hashlib


def snapshot_hash(source_text: str) -> str:
    return hashlib.sha256(source_text.encode("utf-8")).hexdigest()


def render_oracle_module(source_text: str, snapshot_digest: str) -> str:
    """Render the frozen oracle module for RiskEngine._evaluate."""
    tree = ast.parse(source_text)
    target = None
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == "_evaluate":
            target = node
            break
    if target is None:
        raise ValueError("RiskEngine._evaluate not found in source snapshot")
    func = ast.parse(ast.unparse(target)).body[0]
    assert isinstance(func, ast.FunctionDef)
    func.name = "oracle_evaluate"
    func.args.args = [
        ast.arg(arg="policy"),
        ast.arg(arg="request"),
        ast.arg(arg="halted"),
        ast.arg(arg="seen"),
    ]
    body = ast.unparse(func)
    body = body.replace("self._policy", "policy")
    body = body.replace("self._kill_switch.is_halted()", "halted")
    body = body.replace("self._seen_intent_ids", "seen")
    body = body.replace("self._check(", "_ocheck(")
    header = (
        '"""Frozen oracle for risk.engine.evaluate (AUTO-GENERATED, immutable).',
        "",
        f"Snapshot sha256: {snapshot_digest}.",
        "Verification-only: imported by parity tests/harnesses, never by production.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from risk.models import RiskCheck, RiskDecision",
        "from risk.session import SessionRules, clock_sane, within_session",
        "",
        "",
        "def _ocheck(checks: list, name: str, passed: bool, detail: str = '') -> bool:",
        "    checks.append(RiskCheck(name=name, passed=passed, detail=detail))",
        "    return passed",
        "",
        "",
    )
    return "\n".join(header) + body + "\n"


def render_parity_test(unit_id: str, snapshot_digest: str) -> str:
    """Render the generated differential test module for the risk kernel."""
    header_unit = unit_id
    return "\n".join(
        [
            '"""Generated differential parity: frozen oracle vs Rust-backed engine.',
            "",
            f"Unit: {header_unit}.",
            f"Snapshot sha256: {snapshot_digest}.",
            "AUTO-GENERATED by the migration agent — expectations immutable.",
            "The oracle is the pre-migration implementation, frozen verbatim;",
            "the engine must match it exactly on golden + fuzz inputs.",
            '"""',
            "",
            "from __future__ import annotations",
            "",
            "import random",
            "",
            "from risk import RiskEngine, RiskPolicy, RiskRequest",
            "from scripts.migration.agent.kernels import (",
            "    decision_tuple,",
            "    run_risk_fuzz,",
            "    run_risk_parity,",
            ")",
            "",
            "",
            "def test_generated_parity_golden() -> None:",
            "    outcome = run_risk_parity()",
            "    assert outcome.verdict == 'PASS', outcome.mismatches[:5]",
            "    assert outcome.cases > 20",
            "",
            "",
            "def test_generated_parity_fuzz() -> None:",
            "    outcome = run_risk_fuzz(trials=150, seed=909090)",
            "    assert outcome.verdict == 'PASS', outcome.failures[:5]",
            "",
            "",
            "def test_generated_engine_preserves_fail_closed() -> None:",
            "    policy = RiskPolicy()",
            "    request = RiskRequest(",
            '        intent_id="probe",',
            '        strategy_id="s",',
            '        symbol="TEST",',
            '        side="BUY",',
            "        quantity=-5.0,",
            "        price=100.0,",
            '        timestamp="2026-01-05 09:15:00",',
            "    )",
            "    decision = RiskEngine(policy).evaluate(request)",
            "    assert not decision.approved",
            "    assert decision_tuple(decision)[1][0][0] == 'kill_switch'",
            "",
            "",
            "def test_generated_fuzz_is_deterministic() -> None:",
            "    first = run_risk_fuzz(trials=40, seed=4242)",
            "    second = run_risk_fuzz(trials=40, seed=4242)",
            "    assert (first.verdict, first.trials) == (second.verdict, second.trials)",
            "    _ = random.Random(1)",
            "",
        ]
    )


__all__ = ["snapshot_hash", "render_oracle_module", "render_parity_test"]
