"""Generated differential parity: frozen oracle vs Rust-backed engine.

Unit: risk.engine.evaluate.
Snapshot sha256: af07929c1c3a4337811fd397bc912aff63e78eea01d490ebd2c87daeb78b8385.
AUTO-GENERATED by the migration agent — expectations immutable.
The oracle is the pre-migration implementation, frozen verbatim;
the engine must match it exactly on golden + fuzz inputs.
"""

from __future__ import annotations

import random

from risk import RiskEngine, RiskPolicy, RiskRequest
from scripts.migration.agent.kernels import (
    decision_tuple,
    run_risk_fuzz,
    run_risk_parity,
)


def test_generated_parity_golden() -> None:
    outcome = run_risk_parity()
    assert outcome.verdict == "PASS", outcome.mismatches[:5]
    assert outcome.cases > 20


def test_generated_parity_fuzz() -> None:
    outcome = run_risk_fuzz(trials=150, seed=909090)
    assert outcome.verdict == "PASS", outcome.failures[:5]


def test_generated_engine_preserves_fail_closed() -> None:
    policy = RiskPolicy()
    request = RiskRequest(
        intent_id="probe",
        strategy_id="s",
        symbol="TEST",
        side="BUY",
        quantity=-5.0,
        price=100.0,
        timestamp="2026-01-05 09:15:00",
    )
    decision = RiskEngine(policy).evaluate(request)
    assert not decision.approved
    assert decision_tuple(decision)[1][0][0] == "kill_switch"


def test_generated_fuzz_is_deterministic() -> None:
    first = run_risk_fuzz(trials=40, seed=4242)
    second = run_risk_fuzz(trials=40, seed=4242)
    assert (first.verdict, first.trials) == (second.verdict, second.trials)
    _ = random.Random(1)
