//! AUTO-GENERATED by the VAYREN migration agent — do not hand-edit.
//!
//! Source contract: RiskEngine::_evaluate scalar checks. Regenerate
//! from the KernelSpec on any contract change; semantic hand-edits
//! are forbidden (parity would fail).

#[derive(Debug, Clone, Copy)]
pub struct RiskKernelInputs {
    pub request_broker_healthy: bool,
    pub policy_require_fresh_data_seconds_present: bool,
    pub request_data_age_seconds_present: bool,
    pub request_data_age_seconds: f64,
    pub policy_require_fresh_data_seconds: f64,
    pub policy_spread_limit_pct_present: bool,
    pub request_spread_pct_present: bool,
    pub request_spread_pct: f64,
    pub policy_spread_limit_pct: f64,
    pub policy_cooldown_seconds: f64,
    pub request_last_order_epoch_present: bool,
    pub request_now_epoch: f64,
    pub request_last_order_epoch: f64,
    pub policy_max_orders_per_day_present: bool,
    pub request_orders_today: i64,
    pub policy_max_orders_per_day: i64,
    pub request_quantity: f64,
    pub request_price: f64,
    pub policy_max_order_qty: f64,
    pub policy_max_notional_present: bool,
    pub policy_max_notional: f64,
    pub request_position_qty: f64,
    pub side_is_buy: bool,
    pub policy_max_position_qty: f64,
    pub policy_max_exposure_pct_present: bool,
    pub request_equity: f64,
    pub policy_max_exposure_pct: f64,
    pub policy_daily_loss_limit_present: bool,
    pub request_day_pnl: f64,
    pub policy_daily_loss_limit: f64,
    pub policy_strategy_loss_limit_present: bool,
    pub request_strategy_day_pnl: f64,
    pub policy_strategy_loss_limit: f64,
    pub request_available_capital: f64,
}

/// Bit 0: `broker_health`.
pub const BIT_BROKER_HEALTH: u32 = 1 << 0;
/// Bit 1: `fresh_data`.
pub const BIT_FRESH_DATA: u32 = 1 << 1;
/// Bit 2: `spread`.
pub const BIT_SPREAD: u32 = 1 << 2;
/// Bit 3: `cooldown`.
pub const BIT_COOLDOWN: u32 = 1 << 3;
/// Bit 4: `order_rate`.
pub const BIT_ORDER_RATE: u32 = 1 << 4;
/// Bit 5: `sanity`.
pub const BIT_SANITY: u32 = 1 << 5;
/// Bit 6: `order_qty`.
pub const BIT_ORDER_QTY: u32 = 1 << 6;
/// Bit 7: `notional`.
pub const BIT_NOTIONAL: u32 = 1 << 7;
/// Bit 8: `position`.
pub const BIT_POSITION: u32 = 1 << 8;
/// Bit 9: `exposure`.
pub const BIT_EXPOSURE: u32 = 1 << 9;
/// Bit 10: `daily_loss`.
pub const BIT_DAILY_LOSS: u32 = 1 << 10;
/// Bit 11: `strategy_loss`.
pub const BIT_STRATEGY_LOSS: u32 = 1 << 11;
/// Bit 12: `capital`.
pub const BIT_CAPITAL: u32 = 1 << 12;

/// Pure scalar policy checks. Bit i set ⟺ checks[i] passed.
pub fn evaluate_risk_kernel(inputs: &RiskKernelInputs) -> u32 {
    let request_broker_healthy: bool = inputs.request_broker_healthy;
    let policy_require_fresh_data_seconds_present: bool =
        inputs.policy_require_fresh_data_seconds_present;
    let request_data_age_seconds_present: bool = inputs.request_data_age_seconds_present;
    let request_data_age_seconds: f64 = inputs.request_data_age_seconds;
    let policy_require_fresh_data_seconds: f64 = inputs.policy_require_fresh_data_seconds;
    let policy_spread_limit_pct_present: bool = inputs.policy_spread_limit_pct_present;
    let request_spread_pct_present: bool = inputs.request_spread_pct_present;
    let request_spread_pct: f64 = inputs.request_spread_pct;
    let policy_spread_limit_pct: f64 = inputs.policy_spread_limit_pct;
    let policy_cooldown_seconds: f64 = inputs.policy_cooldown_seconds;
    let request_last_order_epoch_present: bool = inputs.request_last_order_epoch_present;
    let request_now_epoch: f64 = inputs.request_now_epoch;
    let request_last_order_epoch: f64 = inputs.request_last_order_epoch;
    let policy_max_orders_per_day_present: bool = inputs.policy_max_orders_per_day_present;
    let request_orders_today: i64 = inputs.request_orders_today;
    let policy_max_orders_per_day: i64 = inputs.policy_max_orders_per_day;
    let request_quantity: f64 = inputs.request_quantity;
    let request_price: f64 = inputs.request_price;
    let policy_max_order_qty: f64 = inputs.policy_max_order_qty;
    let policy_max_notional_present: bool = inputs.policy_max_notional_present;
    let policy_max_notional: f64 = inputs.policy_max_notional;
    let request_position_qty: f64 = inputs.request_position_qty;
    let side_is_buy: bool = inputs.side_is_buy;
    let policy_max_position_qty: f64 = inputs.policy_max_position_qty;
    let policy_max_exposure_pct_present: bool = inputs.policy_max_exposure_pct_present;
    let request_equity: f64 = inputs.request_equity;
    let policy_max_exposure_pct: f64 = inputs.policy_max_exposure_pct;
    let policy_daily_loss_limit_present: bool = inputs.policy_daily_loss_limit_present;
    let request_day_pnl: f64 = inputs.request_day_pnl;
    let policy_daily_loss_limit: f64 = inputs.policy_daily_loss_limit;
    let policy_strategy_loss_limit_present: bool = inputs.policy_strategy_loss_limit_present;
    let request_strategy_day_pnl: f64 = inputs.request_strategy_day_pnl;
    let policy_strategy_loss_limit: f64 = inputs.policy_strategy_loss_limit;
    let request_available_capital: f64 = inputs.request_available_capital;
    let mut mask: u32 = 0;
    if request_broker_healthy {
        mask |= BIT_BROKER_HEALTH;
    }
    if (!policy_require_fresh_data_seconds_present)
        || (request_data_age_seconds_present
            && (request_data_age_seconds <= policy_require_fresh_data_seconds))
    {
        mask |= BIT_FRESH_DATA;
    }
    if (!policy_spread_limit_pct_present)
        || (request_spread_pct_present && (request_spread_pct <= policy_spread_limit_pct))
    {
        mask |= BIT_SPREAD;
    }
    if (!((policy_cooldown_seconds > 0.0) && request_last_order_epoch_present))
        || ((request_now_epoch - request_last_order_epoch) >= policy_cooldown_seconds)
    {
        mask |= BIT_COOLDOWN;
    }
    if (!policy_max_orders_per_day_present) || (request_orders_today < policy_max_orders_per_day) {
        mask |= BIT_ORDER_RATE;
    }
    if !((request_quantity <= 0.0) || (request_price <= 0.0)) {
        mask |= BIT_SANITY;
    }
    if request_quantity <= policy_max_order_qty {
        mask |= BIT_ORDER_QTY;
    }
    if (!policy_max_notional_present) || ((request_quantity * request_price) <= policy_max_notional)
    {
        mask |= BIT_NOTIONAL;
    }
    if ((request_position_qty + ((if side_is_buy { 1.0 } else { -1.0 }) * request_quantity)).abs())
        <= policy_max_position_qty
    {
        mask |= BIT_POSITION;
    }
    if (!(policy_max_exposure_pct_present && (request_equity > 0.0)))
        || ((((((request_position_qty
            + ((if side_is_buy { 1.0 } else { -1.0 }) * request_quantity))
            .abs())
            * request_price)
            / request_equity)
            * 100.0)
            <= policy_max_exposure_pct)
    {
        mask |= BIT_EXPOSURE;
    }
    if (!policy_daily_loss_limit_present) || (request_day_pnl >= (-(policy_daily_loss_limit.abs())))
    {
        mask |= BIT_DAILY_LOSS;
    }
    if (!policy_strategy_loss_limit_present)
        || (request_strategy_day_pnl >= (-(policy_strategy_loss_limit.abs())))
    {
        mask |= BIT_STRATEGY_LOSS;
    }
    if !((request_available_capital <= 0.0) && side_is_buy) {
        mask |= BIT_CAPITAL;
    }
    mask
}
