[workspace]
resolver = "2"
members = ["vayren-core", "vayren-shell", "vayren-portfolio-view", "vayren-live-view", "vayren-research-view", "vayren-system-view", "vayren-strategy-lab-view", "vayren-market-view"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
vayren-core = { path = "vayren-core" }
vayren-shell = { path = "vayren-shell" }
slint = { version = "~1.17.0", default-features = false }
slint-build = { version = "~1.17.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clipboard-win = "5"
i-slint-backend-testing = "~1.17.0"

[profile.dev]
debug = 1

[profile.test]
debug = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

