[workspace]
resolver = "2"
members = ["vayren-core", "vayren-shell", "vayren-portfolio-view", "vayren-live-view", "vayren-research-view", "vayren-system-view", "vayren-strategy-lab-view", "vayren-market-view"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
